

export const LOAD_PORTALS = 'zhihui/Portal/LOAD_PORTALS'
export const LOAD_PORTALS_SUCCESS = 'zhihui/Portal/LOAD_PORTALS_SUCCESS'
export const LOAD_PORTALS_FAILURE = 'zhihui/Portal/LOAD_PORTALS_FAILURE'
export const ADD_PORTAL = 'zhihui/Portal/ADD_PORTAL'
export const ADD_PORTAL_SUCCESS = 'zhihui/Portal/ADD_PORTAL_SUCCESS'
export const ADD_PORTAL_FAILURE = 'zhihui/Portal/ADD_PORTAL_FAILURE'
export const DELETE_PORTAL = 'zhihui/Portal/DELETE_PORTAL'
export const DELETE_PORTAL_SUCCESS = 'zhihui/Portal/DELETE_PORTAL_SUCCESS'
export const DELETE_PORTAL_FAILURE = 'zhihui/Portal/DELETE_PORTAL_FAILURE'
export const EDIT_PORTAL = 'zhihui/Portal/EDIT_PORTAL'
export const EDIT_PORTAL_SUCCESS = 'zhihui/Portal/EDIT_PORTAL_SUCCESS'
export const EDIT_PORTAL_FAILURE = 'zhihui/Portal/EDIT_PORTAL_FAILURE'
export const LOAD_SELECT_TEAMS = 'zhihui/Portal/LOAD_SELECT_TEAMS'
export const LOAD_SELECT_TEAMS_SUCCESS = 'zhihui/Portal/LOAD_SELECT_TEAMS_SUCCESS'
export const LOAD_SELECT_TEAMS_FAILURE = 'zhihui/Portal/LOAD_SELECT_TEAMS_FAILURE'
