

export const LOAD_GROUPS = 'zhihui/Group/LOAD_GROUPS'
export const LOAD_GROUPS_SUCCESS = 'zhihui/Group/LOAD_GROUPS_SUCCESS'
export const LOAD_GROUP_FAILURE = 'zhihui/Group/LOAD_GROUP_FAILURE'
export const ADD_GROUP = 'zhihui/Group/ADD_GROUP'
export const ADD_GROUP_SUCCESS = 'zhihui/Group/ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAILURE = 'zhihui/Group/ADD_GROUP_FAILURE'
export const DELETE_GROUP = 'zhihui/Group/DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'zhihui/Group/DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAILURE = 'zhihui/Group/DELETE_GROUP_FAILURE'
// export const LOAD_GROUP_DETAIL = 'zhihui/Group/LOAD_GROUP_DETAIL'
// export const LOAD_GROUP_DETAIL_SUCCESS = 'zhihui/Group/LOAD_GROUP_DETAIL_SUCCESS'
export const EDIT_GROUP = 'zhihui/Group/EDIT_GROUP'
export const EDIT_GROUP_SUCCESS = 'zhihui/Group/EDIT_GROUP_SUCCESS'
export const EDIT_GROUP_FAILURE = 'zhihui/Group/EDIT_GROUP_FAILURE'
