

export const LOAD_WIDGETS = 'zhihui/Widget/LOAD_WIDGETS'
export const LOAD_WIDGETS_SUCCESS = 'zhihui/Widget/LOAD_WIDGETS_SUCCESS'
export const LOAD_WIDGETS_FAILURE = 'zhihui/Widget/LOAD_WIDGETS_FAILURE'
export const ADD_WIDGET = 'zhihui/Widget/ADD_WIDGET'
export const ADD_WIDGET_SUCCESS = 'zhihui/Widget/ADD_WIDGET_SUCCESS'
export const ADD_WIDGET_FAILURE = 'zhihui/Widget/ADD_WIDGET_FAILURE'
export const LOAD_WIDGET_DETAIL = 'zhihui/Widget/LOAD_WIDGET_DETAIL'
export const LOAD_WIDGET_DETAIL_SUCCESS = 'zhihui/Widget/LOAD_WIDGET_DETAIL_SUCCESS'
export const LOAD_WIDGET_DETAIL_FAILURE = 'zhihui/Widget/LOAD_WIDGET_DETAIL_FAILURE'
export const EDIT_WIDGET = 'zhihui/Widget/EDIT_WIDGET'
export const EDIT_WIDGET_SUCCESS = 'zhihui/Widget/EDIT_WIDGET_SUCCESS'
export const EDIT_WIDGET_FAILURE = 'zhihui/Widget/EDIT_WIDGET_FAILURE'
export const DELETE_WIDGET = 'zhihui/Widget/DELETE_WIDGET'
export const DELETE_WIDGET_SUCCESS = 'zhihui/Widget/DELETE_WIDGET_SUCCESS'
export const DELETE_WIDGET_FAILURE = 'zhihui/Widget/DELETE_WIDGET_FAILURE'
export const CLEAR_CURRENT_WIDGET = 'zhihui/Widget/CLEAR_CURRENT_WIDGET'
export const EXECUTE_COMPUTED_SQL = 'zhihui/Widget/EXECUTE_COMPUTED_SQL'
