

export const LOAD_PROJECTS = 'zhihui/Project/LOAD_PROJECTS'
export const LOAD_PROJECTS_SUCCESS = 'zhihui/Project/LOAD_PROJECTS_SUCCESS'
export const LOAD_PROJECTS_FAILURE = 'zhihui/Project/LOAD_PROJECTS_FAILURE'
export const ADD_PROJECT = 'zhihui/Project/ADD_PROJECT'
export const ADD_PROJECT_SUCCESS = 'zhihui/Project/ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_FAILURE = 'zhihui/Project/ADD_PROJECT_FAILURE'
export const EDIT_PROJECT = 'zhihui/Project/EDIT_PROJECT'
export const EDIT_PROJECT_SUCCESS = 'zhihui/Project/EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_FAILURE = 'zhihui/Project/EDIT_PROJECT_FAILURE'
export const TRANSFER_PROJECT = 'zhihui/Project/TRANSFER_PROJECT'
export const TRANSFER_PROJECT_SUCCESS = 'zhihui/Project/TRANSFER_PROJECT_SUCCESS'
export const TRANSFER_PROJECT_FAILURE = 'zhihui/Project/TRANSFER_PROJECT_FAILURE'
export const DELETE_PROJECT = 'zhihui/Project/DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'zhihui/Project/DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'zhihui/Project/DELETE_PROJECT_FAILURE'
export const LOAD_PROJECT_DETAIL = 'zhihui/Project/LOAD_PROJECT_DETAIL'
export const LOAD_PROJECT_DETAIL_SUCCESS = 'zhihui/Project/LOAD_PROJECT_DETAIL_SUCCESS'
export const LOAD_PROJECT_DETAIL_FAILURE = 'zhihui/Project/LOAD_PROJECT_DETAIL_FAILURE'
export const KILL_PROJECT_DETAIL = 'zhihui/Project/KILL_PROJECT_DETAIL'
export const SEARCH_PROJECT = 'zhihui/Project/SEARCH_PROJECT'
export const SEARCH_PROJECT_SUCCESS = 'zhihui/Project/SEARCH_PROJECT_SUCCESS'
export const SEARCH_PROJECT_FAILURE = 'zhihui/Project/SEARCH_PROJECT_FAILURE'

export const GET_PROJECT_STAR_USER = 'zhihui/Project/GET_PROJECT_STAR_USER'
export const GET_PROJECT_STAR_USER_SUCCESS = 'zhihui/Project/GET_PROJECT_STAR_USER_SUCCESS'
export const GET_PROJECT_STAR_USER_FAILURE = 'zhihui/Project/GET_PROJECT_STAR_USER_FAILURE'

export const PROJECT_UNSTAR = 'zhihui/Project/PROJECT_UNSTAR'
export const PROJECT_UNSTAR_SUCCESS = 'zhihui/Project/PROJECT_UNSTAR_SUCCESS'
export const PROJECT_UNSTAR_FAILURE = 'zhihui/Project/PROJECT_UNSTAR_FAILURE'

export const LOAD_COLLECT_PROJECTS = 'zhihui/Project/LOAD_COLLECT_PROJECTS'
export const LOAD_COLLECT_PROJECTS_SUCCESS = 'zhihui/Project/LOAD_COLLECT_PROJECTS_SUCCESS'
export const LOAD_COLLECT_PROJECTS_FAILURE = 'zhihui/Project/LOAD_COLLECT_PROJECTS_FAILURE'

export const CLICK_COLLECT_PROJECT = 'zhihui/Project/CLICK_COLLECT_PROJECT'
export const CLICK_COLLECT_PROJECT_SUCCESS = 'zhihui/Project/CLICK_COLLECT_PROJECT_SUCCESS'
export const CLICK_COLLECT_PROJECT_FAILURE = 'zhihui/Project/CLICK_COLLECT_PROJECT_FAILURE'

export const ADD_PROJECT_ADMIN = 'zhihui/Project/ADD_PROJECT_ADMIN'
export const ADD_PROJECT_ADMIN_SUCCESS = 'zhihui/Project/ADD_PROJECT_ADMIN_SUCCESS'
export const ADD_PROJECT_ADMIN_FAIL = 'zhihui/Project/ADD_PROJECT_ADMIN_FAIL'

export const DELETE_PROJECT_ADMIN = 'zhihui/Project/DELETE_PROJECT_ADMIN'
export const DELETE_PROJECT_ADMIN_SUCCESS = 'zhihui/Project/DELETE_PROJECT_ADMIN_SUCCESS'
export const DELETE_PROJECT_ADMIN_FAIL = 'zhihui/Project/DELETE_PROJECT_ADMIN_FAIL'

export const ADD_PROJECT_ROLE = 'zhihui/Project/ADD_PROJECT_ROLE'
export const ADD_PROJECT_ROLE_SUCCESS = 'zhihui/Project/ADD_PROJECT_ROLE_SUCCESS'
export const ADD_PROJECT_ROLE_FAIL = 'zhihui/Project/ADD_PROJECT_ROLE_FAIL'

export const DELETE_PROJECT_ROLE = 'zhihui/Project/DELETE_PROJECT_ROLE'
export const DELETE_PROJECT_ROLE_SUCCESS = 'zhihui/Project/DELETE_PROJECT_ROLE_SUCCESS'
export const DELETE_PROJECT_ROLE_FAIL = 'zhihui/Project/DELETE_PROJECT_ROLE_FAIL'

export const UPDATE_RELATION_ROLE_PROJECT = 'zhihui/Project/UPDATE_RELATION_ROLE_PROJECT'
export const UPDATE_RELATION_ROLE_PROJECT_SUCCESS = 'zhihui/Project/UPDATE_RELATION_ROLE_PROJECT_SUCCESS'
export const UPDATE_RELATION_ROLE_PROJECT_FAIL = 'zhihui/Project/UPDATE_RELATION_ROLE_PROJECT_FAIL'

export const LOAD_RELATION_ROLE_PROJECT = 'zhihui/Project/LOAD_RELATION_ROLE_PROJECT'
export const RELATION_ROLE_PROJECT_LOADED = 'zhihui/Project/RELATION_ROLE_PROJECT_LOADED'
export const LOAD_RELATION_ROLE_PROJECT_FAIL = 'zhihui/Project/LOAD_RELATION_ROLE_PROJECT_FAIL'

export const DELETE_RELATION_ROLE_PROJECT = 'zhihui/Project/DELETE_RELATION_ROLE_PROJECT'
export const DELETE_RELATION_ROLE_PROJECT_SUCCESS = 'zhihui/Project/DELETE_RELATION_ROLE_PROJECT_SUCCESS'
export const DELETE_RELATION_ROLE_PROJECT_FAIL = 'zhihui/Project/DELETE_RELATION_ROLE_PROJECT_FAIL'

export const EXCLUDE_ROLES = 'zhihui/Project/EXCLUDE_ROLES'
export const EXCLUDE_ROLES_SUCCESS = 'zhihui/Project/EXCLUDE_ROLES_SUCCESS'
export const EXCLUDE_ROLES_FAIL = 'zhihui/Project/EXCLUDE_ROLES_FAIL'

