#配置自己项目的绝对路径
DAVINCI3_HOME:
  /Users/ghy/workplace/zhihui

file:
  userfiles-path: ${DAVINCI3_HOME}/userfiles/
  web_resources: ${DAVINCI3_HOME}/zhihui-ui/
  phantomJs-path: ${DAVINCI3_HOME}/bin/phantom.js

server:
  protocol: http
  address: 60.205.186.13
  port: 8987

  servlet:
    context-path: /


spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
      enabled: true

  config:
    location: classpath:/
    additional-location: file:${DAVINCI3_HOME}/config/
    name: application

  datasource:
    url: jdbc:mysql://60.205.186.13:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10
    type: com.alibaba.druid.pool.DruidDataSource
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat
    break-after-acquire-failure: true
    connection-error-retry-attempts: 3
    validation-query: SELECT 1

  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, file:${file.userfiles-path}, file:${file.web_resources}

  mvc:
    static-path-pattern: /**

  ## redis config
  ## please choose either of the two ways
  redis:
    isEnable: false

    ## standalone config
    host: 60.205.186.13
    port: 6379

    ## cluster config
    #  cluster:
    #       nodes:

    password:
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

  ## mail is one of the important configuration of the application
  ## mail config cannot be null or empty
  ## some mailboxes need to be set separately password for the SMTP service)
  mail:
    host: smtp.163.com
    port: 465
    username: gaohaiyang_cn@163.com
    password: Gao123456
    nickname: zhihui

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true

  ldap:
    urls:
    username:
    password:
    base:
    domainName:    # domainName 指 企业邮箱后缀，如企业邮箱为：xxx@example.com, 这里值为 '@example.com'


  thymeleaf:
    mode: HTML
    cache: true
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: true
    template-resolver-order: 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cache:
    caffeine:
      type: caffeine


logging:
  config: file:${DAVINCI3_HOME}/config/logback.xml

springfox:
  documentation:
    swagger:
      v2:
        path: /api-doc


pagehelper:
  supportMethodsArguments: true
  reasonable: true
  returnPageInfo: check
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.huilan.zhihui.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

mapper:
  identity: MYSQL
  not-empty: false
  mappers: com.huilan.zhihui.dao

sql_template_delimiter: $

custom-datasource-driver-path: ${DAVINCI3_HOME}/config/datasource_driver.yml

phantomjs_home: /Users/ghy/phantomjs-2.1.1-macosx/bin/phantomjs

data-auth-center:
  channels:
    - name:
      base-url:
      auth-code: