

export const LOAD_ORGANIZATIONS = 'zhihui/Organization/LOAD_ORGANIZATIONS'
export const LOAD_ORGANIZATIONS_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATIONS_SUCCESS'
export const LOAD_ORGANIZATIONS_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATIONS_FAILURE'
export const ADD_ORGANIZATION = 'zhihui/Organization/ADD_ORGANIZATION'
export const ADD_ORGANIZATION_SUCCESS = 'zhihui/Organization/ADD_ORGANIZATION_SUCCESS'
export const ADD_ORGANIZATION_FAILURE = 'zhihui/Organization/ADD_ORGANIZATION_FAILURE'

export const EDIT_ORGANIZATION = 'zhihui/Organization/EDIT_ORGANIZATION'
export const EDIT_ORGANIZATION_SUCCESS = 'zhihui/Organization/EDIT_ORGANIZATION_SUCCESS'
export const EDIT_ORGANIZATION_FAILURE = 'zhihui/Organization/EDIT_ORGANIZATION_FAILURE'

export const DELETE_ORGANIZATION = 'zhihui/Organization/DELETE_ORGANIZATION'
export const DELETE_ORGANIZATION_SUCCESS = 'zhihui/Organization/DELETE_ORGANIZATION_SUCCESS'
export const DELETE_ORGANIZATION_FAILURE = 'zhihui/Organization/DELETE_ORGANIZATION_FAILURE'

export const LOAD_ORGANIZATION_DETAIL = 'zhihui/Organization/LOAD_ORGANIZATION_DETAIL'
export const LOAD_ORGANIZATION_DETAIL_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATION_DETAIL_SUCCESS'
export const LOAD_ORGANIZATION_DETAIL_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATION_DETAIL_FAILURE'

export const LOAD_ORGANIZATIONS_PROJECTS = 'zhihui/Organization/LOAD_ORGANIZATIONS_PROJECTS'
export const LOAD_ORGANIZATIONS_PROJECTS_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATIONS_PROJECTS_SUCCESS'
export const LOAD_ORGANIZATIONS_PROJECTS_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATIONS_PROJECTS_FAILURE'

export const LOAD_ORGANIZATIONS_MEMBERS = 'zhihui/Organization/LOAD_ORGANIZATIONS_MEMBERS'
export const LOAD_ORGANIZATIONS_MEMBERS_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATIONS_MEMBERS_SUCCESS'
export const LOAD_ORGANIZATIONS_MEMBERS_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATIONS_MEMBERS_FAILURE'

export const LOAD_ORGANIZATIONS_TEAMS = 'zhihui/Organization/LOAD_ORGANIZATIONS_TEAMS'
export const LOAD_ORGANIZATIONS_TEAMS_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATIONS_TEAMS_SUCCESS'
export const LOAD_ORGANIZATIONS_TEAMS_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATIONS_TEAMS_FAILURE'

export const ADD_TEAM = 'zhihui/Organization/ADD_TEAM'
export const ADD_TEAM_SUCCESS = 'zhihui/Organization/ADD_TEAM_SUCCESS'
export const ADD_TEAM_FAILURE = 'zhihui/Organization/ADD_TEAM_FAILURE'

export const SEARCH_MEMBER = 'zhihui/Organization/SEARCH_MEMBER'
export const SEARCH_MEMBER_SUCCESS = 'zhihui/Organization/SEARCH_MEMBER_SUCCESS'
export const SEARCH_MEMBER_FAILURE = 'zhihui/Organization/SEARCH_MEMBER_FAILURE'

export const INVITE_MEMBER = 'zhihui/Organization/INVITE_MEMBER'
export const INVITE_MEMBER_SUCCESS = 'zhihui/Organization/INVITE_MEMBER_SUCCESS'
export const INVITE_MEMBER_FAILURE = 'zhihui/Organization/INVITE_MEMBER_FAILURE'

export const DELETE_ORGANIZATION_MEMBER = 'zhihui/Organization/DELETE_ORGANIZATION_MEMBER'
export const DELETE_ORGANIZATION_MEMBER_SUCCESS = 'zhihui/Organization/DELETE_ORGANIZATION_MEMBER_SUCCESS'
export const DELETE_ORGANIZATION_MEMBER_ERROR = 'zhihui/Organization/DELETE_ORGANIZATION_MEMBER_ERROR'

export const CHANGE_MEMBER_ROLE_ORGANIZATION = 'zhihui/Organization/CHANGE_MEMBER_ROLE_ORGANIZATION'
export const CHANGE_MEMBER_ROLE_ORGANIZATION_SUCCESS = 'zhihui/Organization/CHANGE_MEMBER_ROLE_ORGANIZATION_SUCCESS'
export const CHANGE_MEMBER_ROLE_ORGANIZATION_ERROR = 'zhihui/Organization/CHANGE_MEMBER_ROLE_ORGANIZATION_ERROR'


export const LOAD_ORGANIZATIONS_ROLE = 'zhihui/Organization/LOAD_ORGANIZATIONS_ROLE'
export const LOAD_ORGANIZATIONS_ROLE_SUCCESS = 'zhihui/Organization/LOAD_ORGANIZATIONS_ROLE_SUCCESS'
export const LOAD_ORGANIZATIONS_ROLE_FAILURE = 'zhihui/Organization/LOAD_ORGANIZATIONS_ROLE_FAILURE'

export const ADD_ROLE = 'zhihui/Organization/ADD_ROLE'
export const ADD_ROLE_SUCCESS = 'zhihui/Organization/ADD_ROLE_SUCCESS'
export const ADD_ROLE_FAILURE = 'zhihui/Organization/ADD_ROLE_FAILURE'

export const DELETE_ROLE = 'zhihui/Organization/DELETE_ROLE'
export const DELETE_ROLE_SUCCESS = 'zhihui/Organization/DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_FAILURE = 'zhihui/Organization/DELETE_ROLE_FAILURE'

export const EDIT_ROLE = 'zhihui/Organization/EDIT_ROLE'
export const EDIT_ROLE_SUCCESS = 'zhihui/Organization/DEIT_ROLE_SUCCESS'
export const EDIT_ROLE_FAILURE = 'zhihui/Organization/EDIT_ROLE_FAILURE'

export const REL_ROLE_MEMBER = 'zhihui/Organization/DELETE_ROLE/REL_ROLE_MEMBER'
export const REL_ROLE_MEMBER_SUCCESS = 'zhihui/Organization/DELETE_ROLE/REL_ROLE_MEMBER_SUCCESS'
export const REL_ROLE_MEMBER_FAILURE = 'zhihui/Organization/DELETE_ROLE/REL_ROLE_MEMBER_FAILURE'

export const GET_REL_ROLE_MEMBER = 'zhihui/Organization/DELETE_ROLE/GET_REL_ROLE_MEMBER'
export const GET_REL_ROLE_MEMBER_SUCCESS = 'zhihui/Organization/DELETE_ROLE/GET_REL_ROLE_MEMBER_SUCCESS'
export const GET_REL_ROLE_MEMBER_FAILURE = 'zhihui/Organization/DELETE_ROLE/GET_REL_ROLE_MEMBER_FAILURE'

export const SET_CURRENT_ORIGANIZATION_PROJECT = 'zhihui/Organization//GET_REL_ROLE_MEMBER'

export const LOAD_PROJECT_ADMINS = 'zhihui/Organization//LOAD_PROJECT_ADMINS'
export const LOAD_PROJECT_ADMINS_SUCCESS = 'zhihui/Organization//LOAD_PROJECT_ADMINS_SUCCESS'
export const LOAD_PROJECT_ADMINS_FAIL = 'zhihui/Organization//LOAD_PROJECT_ADMINS_FAIL'

export const LOAD_PROJECT_ROLES = 'zhihui/Project/LOAD_PROJECT_ROLES'
export const LOAD_PROJECT_ROLES_SUCCESS = 'zhihui/Project/LOAD_PROJECT_ROLES_SUCCESS'
export const LOAD_PROJECT_ROLES_FAIL = 'zhihui/Project/LOAD_PROJECT_ROLES_FAIL'

export const GET_VIZ_VISBILITY = 'zhihui/Project/GET_VIZ_VISBILITY'
export const POST_VIZ_VISBILITY = 'zhihui/Project/POST_VIZ_VISBILITY'
