

export const LOAD_USERS = 'zhihui/User/LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'zhihui/User/LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAILURE = 'zhihui/User/LOAD_USERS_FAILURE'
export const ADD_USER = 'zhihui/User/ADD_USER'
export const ADD_USER_SUCCESS = 'zhihui/User/ADD_USER_SUCCESS'
export const ADD_USER_FAILURE = 'zhihui/User/ADD_USER_FAILURE'
export const DELETE_USER = 'zhihui/User/DELETE_USER'
export const DELETE_USER_SUCCESS = 'zhihui/User/DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'zhihui/User/DELETE_USER_FAILURE'
// export const LOAD_USER_DETAIL = 'zhihui/User/LOAD_USER_DETAIL'
// export const LOAD_USER_DETAIL_SUCCESS = 'zhihui/User/LOAD_USER_DETAIL_SUCCESS'
export const LOAD_USER_GROUPS = 'zhihui/User/LOAD_USER_GROUPS'
export const LOAD_USER_GROUPS_SUCCESS = 'zhihui/User/LOAD_USER_GROUPS_SUCCESS'
export const LOAD_USER_GROUPS_FAILURE = 'zhihui/User/LOAD_USER_GROUPS_FAILURE'
export const EDIT_USER_INFO = 'zhihui/User/EDIT_USER_INFO'
export const EDIT_USER_INFO_SUCCESS = 'zhihui/User/EDIT_USER_INFO_SUCCESS'
export const EDIT_USER_INFO_FAILURE = 'zhihui/User/EDIT_USER_INFO_FAILURE'
export const CHANGE_USER_PASSWORD = 'zhihui/User/CHANGE_USER_PASSWORD'
export const CHANGE_USER_PASSWORD_SUCCESS = 'zhihui/User/CHANGE_USER_PASSWORD_SUCCESS'
export const CHANGE_USER_PASSWORD_FAILURE = 'zhihui/User/CHANGE_USER_PASSWORD_FAILURE'
